name: GitHub Environment Secrets

on:
  workflow_dispatch:  # You can also add schedule: for automated runs

jobs:
  fetch-environment-secrets:
    runs-on: ubuntu-latest

    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      GH_ORG: ${{ secrets.GH_ORG }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Debug – list all files
        run: ls -R

      - name: Run script to fetch environment secrets
        run: |
          if [ -f fetch_environment_secrets.py ]; then
            python fetch_environment_secrets.py
          else
            echo "❌ Script 'fetch_environment_secrets.py' not found!"
            exit 1
          fi

      - name: Upload generated CSV
        uses: actions/upload-artifact@v4
        with:
          name: environment-secrets-report
          path: github_environment_secrets.csv
