name: GitHub Org Runner variables secrets

on:
  workflow_dispatch:  # Manual trigger

jobs:
  fetch-org-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv requests

      - name: Set up environment variables
        run: |
          echo "GH_PAT=${{ secrets.GH_PAT }}" >> .env
          echo "GH_ORG=${{ secrets.GH_ORG }}" >> .env

      - name: Run fetch script
        run: |
          python fetch_org_runners_variables_secrets.py  

      - name: Upload generated CSV files
        uses: actions/upload-artifact@v4
        with:
          name: org-config-csvs
          path: |
            github_runners_*.csv
            github_secrets_*.csv
            github_variables_*.csv
