name: GitHub Org Repo Audit

on:
  workflow_dispatch: 

jobs:
  audit-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Repo Audit Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_NAME: ${{ secrets.ORG_NAME }}
        run: |
          python fetch_repo_details(inventory).py

      - name: Upload CSV Output
        uses: actions/upload-artifact@v4
        with:
          name: repo-audit-results
          path: "*.csv"
