name: GitHub Inventory Details

on:
  workflow_dispatch:  # You can also use `schedule:` for daily/weekly runs

jobs:
  audit-org-repos:
    runs-on: ubuntu-latest

    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      GH_ORG: ${{ secrets.GH_ORG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run repo audit script
        run: python fetch_repo_details_inventory.py

      - name: Upload output CSV
        uses: actions/upload-artifact@v4
        with:
          name: repo-audit-report
          path: output/*.csv
