name: Variables and Values

on:
  workflow_dispatch:  # Manual trigger via GitHub UI
 

jobs:
  fetch-org-variables:
    runs-on: ubuntu-latest

    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      GH_ORG: ${{ secrets.GH_ORG }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run variables fetch script
        run: python fetch_variables_values.py

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: variables-inventory
          path: |
            org_actions_variables.csv
            error_logs/*.log
